AirLabsTeam/air-core

.eslintrc.js, .huskyrc, @types/styled-components.d.ts, package.json, packages/eslint-config/index.js
So this happened https://github.com/AirLabsTeam/next/pull/185 (private repo, sorry open source world)... and [this rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) will prevent that.
=> fix: add lint rule to prevent extaneous imports

packages/zephyr/src/theme/index.ts
@andyhqtran is it valid to have things like: `MozAnimationDirection`, `WebkitAlignContent`, or `msTransformOrigin` as a key in the TX prop?
=> Tweak allowed CSS properties in TX prop

packages/zephyr/src/Text.tsx, packages/zephyr/stories/Text.stories.tsx
The current implementation only allows the "as" prop to be `undefined` or `'div'` yielding a few type errors throughout the app. Additionally, the v4 didnt have duck-typing working when "as" was defined. This will resolve that issue.
=> Fix type issue with "as" prop on <Text>

packages/zephyr/src/Button.tsx, packages/zephyr/src/Text.tsx
It was incorrect to suggest that "ref" was a valid prop. It's valid to pass as a prop to the actual
component, but ref is technically never a valid prop for a function component
BREAKING CHANGE: Remove "ref" from ButtonProps and TextProps
=> Remove "ref" from the prop typings for both Button and Text

packages/zephyr/src/theme/variants/text.ts
`fontFeatureSettings` for an alternate character set of Gelica we're using.
One example of the difference is the lowercase 'g' with an open tail instead of a loop-tail.
=> feat(zephyr/text): update fontFeatureSettings for text heading variants

packages/zephyr/src/theme/variants/button.ts
Some variants still showed hover styling while disabled, fixed in variants style object
=> Fix: disable hover styling on disabled buttons

packages/zephyr/package.json, packages/zephyr/src/Button.tsx, packages/zephyr/src/theme/variants/button.ts, packages/zephyr/stories/buttons/FilledButton.stories.tsx, packages/zephyr/stories/buttons/GhostButton.stories.tsx, packages/zephyr/stories/buttons/OutlineButton.stories.tsx, yarn.lock
Add loading state to filled button components
- `isLoading` can only be true for buttons with boundaries (ie. filled and outline buttons)
- Note: There is currently no `button-outline-destructive` variant
- `invariant` throws dev side error on build if `isLoading` is set to true for ghost or unstyled variants
- Accessibility
- `useReducedMotion` to [limit animations](https://www.framer.com/api/motion/guide-accessibility/)
- `VisuallyHidden` for meaningful [loading](https://reach.tech/visually-hidden/) state change on screen readers
All comments and full commit history [here](https://github.com/AirLabsTeam/air-core/pull/69)
[Figma](https://www.figma.com/file/EZ1hzsmsNYblYoBQYvVgEV/Web-Component-Library?node-id=26%3A336) Design spec
=> Button `isLoading` prop

packages/zephyr/src/Button.tsx, packages/zephyr/src/theme/variants/button.ts, packages/zephyr/stories/buttons/Button.stories.tsx
- Fix css properties getting inherited when using different variant styles in a responsive array
- Fix button variant typescript def
=> fix(@air/zephyr): fix button responsive variants and type defs

packages/zephyr/src/theme/variants/text.ts
fix ACQ-82
- Add in `text-heading-80` text variant
=> feat(@air/zephyr): add in `text-heading-80` text variant

packages/zephyr/src/Forms/Input.tsx, packages/zephyr/src/Forms/SingleSelect.tsx
… single selects, plus a11y fix
Ensured that the testid prop also constructs testids for the description element + the error element
when rendered.
Additionally, prevented screen readers from hearing error twice.
=> form-improvements (from kyle)

packages/icons/src/svgs/uncategorized/GoogleDrive.svg
I add `class` attribute to each path, since `id` did not prevent merging
=> fix: add class to GoogleDrive paths to avoid merging them

packages/zephyr/src/Modals/Modal.tsx
No longer will people be able to pass empty strings
=> fix(@air/zephyr/modal): require modal label

packages/zephyr/src/IconButton.tsx, packages/zephyr/src/XButton.tsx, packages/zephyr/stories/buttons/IconButton.stories.tsx
Was working on integrating IconButton in the app repo when suddenly...
BREAKING CHANGE
... but we dont use this yet so it wont hurt ❤️
=> For IconButton, rename "hiddenLabel" prop to "children"

packages/zephyr/src/Tooltip.tsx
Radix Trigger type is default as button, this stops non-button elements to have buton styles applied
in Safari
=> fix(tooltip): set Trigger type as undefined

packages/zephyr/src/Portal.tsx
@reach/portal has a default export so needs to be imported then exported as a const instead
BREAKING CHANGE: If you used previous Portal component in its 2hr lifetime you’ll need to use
<Portal> instead of <Portal.Root> (from radix)
=> fix(portal): use correct export expression for Portal

packages/zephyr/src/Menus/components/MenuItem.tsx
Can't believe I didn't notice this in Chromatic 🤦 
- Remove `mt` spacing from `MenuItem`
=> fix(@air/zephyr): fix additional spacing above menu item

packages/zephyr/src/Menus/abstractions/DropdownMenu.tsx
- Prevent clicking on menu item from triggering a click event on parent
=> fix(@air/zephyr): prevent clicking on menu item from triggering a click event on parent

packages/zephyr/src/Menus/components/MenuItem.tsx, packages/zephyr/src/Menus/components/MenuItemDescription.tsx, packages/zephyr/src/Menus/components/MenuItemLabel.tsx, packages/zephyr/src/Menus/index.tsx
Broke out `MenuItemLabel` and `MenuItemDescription` into separate components so the consumers can re-use them and style them if needed
=> chore: export menu item label and description for reuse

packages/zephyr/src/Modals/Modal.tsx
By having this extra element, it breaks potential usages of `display: flex` with their consumers who might be trying to utilize `flex: 1` to get the content to take up the full width of the modal
=> Remove modal content Text wrapper

packages/zephyr/src/Forms/SingleSelect.tsx, packages/zephyr/stories/forms/SingleSelect.stories.tsx
base styles from react-select provide 16px height for non-searchable single-select, and 24px for searchable. No reason for either height, 100% works fine in both cases.
=> fix: s4 - SingleSelect cuts off g

packages/zephyr/src/Modals/TransactionModal.tsx, packages/zephyr/stories/modals/TransactionModal.stories.tsx
- allows object syntax to be used for tertiaryCTAs on the TransactionModal
- This does mean we needed to pick a default button so we went with the destructive since it's the one most likely to be used (and it is distinctly different from the other CTAs)
=> feat: allow object syntax use with TertiaryCTAs

packages/zephyr/src/Forms/Input.tsx
- Conditionally displays the specific formikError on the Input
- This is needed because if we want to display the error on a field, in a place that is **_not_** right below the input, (i.e. using Formik's `ErrorMessage` component) this Input component will still display its error. In which case we end up showing duplicate (and potentially ill-formatted) error messages
=> fix/conditionally display field error on Input

packages/zephyr/src/RadixMenu/components/RadixMenuItem.tsx
Rendering them directly in `.radix-menu-item` rather than in its container.
=> Fix test ids radix menus

packages/zephyr/src/IconButton.tsx, packages/zephyr/stories/buttons/IconButton.stories.tsx
- [Notion Link](https://www.notion.so/airinc/Frontend-3182e6ca45c7469eb0cf7295f925f383?p=2beee74eb7474bd28f603b80e24da4ba)
- Removes the `hasTooltip` prop from IconButton (this is a breaking change)
- Adds a `tooltip` prop on the IconButton to allow passing in the props needed for the IconButton to render a tooltip
=> task/allow iconButton to render tooltip

packages/zephyr/src/IconButton.tsx, packages/zephyr/src/Tooltip.tsx, packages/zephyr/stories/Tooltip.stories.tsx, packages/zephyr/stories/buttons/IconButton.stories.tsx
[Notion Link](https://www.notion.so/airinc/Frontend-3182e6ca45c7469eb0cf7295f925f383?p=2beee74eb7474bd28f603b80e24da4ba)
- adds `tooltip` and `showAssistiveText` prop on IconButton
- BREAKING CHANGE: removes the hasTooltip prop
=> feat/tooltip prop on IconButton

packages/zephyr/src/Button.tsx, packages/zephyr/src/ButtonLink.tsx, packages/zephyr/stories/buttons/ButtonLink.stories.tsx
ButtonLink
- copy usage of `PropsWithAs` and `forwardRefWithAs` from Button component to pass access to anchor HTML attributes
- tested and updated in Storybook
Button
- remove outdated comment
=> Fix: ButtonLink

packages/zephyr/src/RadixMenu/abstractions/RadixDropdownMenu.tsx
When `dir` is not provided, `useDirection` kicks a loop to listen to changes to users reading
direction. This is not helpful to us.
=> fix: add prop to RadixMenu.Root to prevent looping code

packages/zephyr/src/RadixMenu/components/RadixMenuItem.tsx, packages/zephyr/src/RadixMenu/components/RadixMenuItemDivider.tsx
- Modifies props to allow for a divider
- Aim is to support [something like this](https://www.figma.com/file/aQuCRzJj83m2MU3RCwe8dk/UX-Fast---Q4.21?node-id=131%3A275385)
=> feat: add divider to radixMenuItemRenderProps

_templates/zephyr/component/component.ejs.t, packages/zephyr/src/Box.tsx, packages/zephyr/src/Button.tsx, packages/zephyr/src/ButtonLink.tsx, packages/zephyr/src/Forms/InputPrimitive.tsx, packages/zephyr/src/Forms/LabelPrimitive.tsx, packages/zephyr/src/Menus/components/MenuItem.tsx, packages/zephyr/src/Modals/ModalContent.tsx, packages/zephyr/src/Modals/ModalOverlay.tsx, packages/zephyr/src/Text.tsx
BREAKING CHANGE: All `baseStyles` usage has been removed and is no longer a supported API
=> refactor(@air/zephyr): remove baseStyles prop support

packages/zephyr/src/EditableText/EditableTextTextarea.tsx, packages/zephyr/src/EditableText/index.tsx, packages/zephyr/src/Forms/TextareaPrimitive.tsx, packages/zephyr/src/Forms/index.ts, packages/zephyr/stories/forms/TextareaPrimitive.stories.tsx
adds a `TextareaPrimative` which is now the base textarea consumed by `EditableText`, and can also be used on its own.
=> feat(@air/zephyr): add a textarea primative
