packages/zephyr/src/theme/colors.ts

We are changing the values of the key names in the color system from tens to hundreds.
---
BREAKING CHANGE: We are changing the key names of the color system. i.e. `pigeon0.5` -> `pigeon50`,
`pigeon1` -> `pigeon100`

fix(@air/zephyr): change color system to be in the hundreds

---

packages/zephyr/src/theme/index.ts

- Add in individual theme value exports

fix(@air/zephyr): add in theme exports

---

packages/zephyr/src/theme/colors.ts

fix(@air/zephyr): add in missing # to the pigeon50 value

---

@types/styled-components.d.ts
package.json
packages/zephyr/src/Box.tsx
packages/zephyr/src/theme/index.ts
scripts/tsc.sh

- Resolved issue with spreading tx values into each other
- [Made note to move all theme values into this repo](https://www.notion.so/airinc/Move-all-theme-defs-into-air-core-9d9fc748703d40b29902f6c8372a92e2)
- Added some bullshit in `package.json` so I can stop fuckin' my life up in this repo.

Fix TXProp typing

---

packages/zephyr/src/theme/space.ts

feat: expand valid space theme key values

---

packages/zephyr/src/Modals/Modal.tsx

Correctly pass ref thru to close button

---

packages/zephyr/src/theme/colors.ts
packages/zephyr/stories/Colors.stories.tsx

- Some macaw and pigeon values have changed without their name changing
- Add a story for previewing our color palette.
- No longer will we have `color0`. Any colors that were 0 value should now be a different number.

Edit some color names and values

---

packages/zephyr/src/theme/colors.ts
packages/zephyr/stories/Colors.stories.tsx

Just re-doing this cuz I messed up commit messages.

Edit colors and add story

---

packages/zephyr/src/theme/variants/button.ts
packages/zephyr/stories/buttons/FilledButton.stories.tsx

[Notion ticket](https://www.notion.so/airinc/On-call-70de8c5ce7c14404ba8e455f4c4cbfea?p=59bfe58d276f4b7e8c30c7ed04e6e46b)
Add disabled states for filled buttons and update rogue color numbers

fix(@air/zephyr/button): add disabled filled button states

---

packages/zephyr/src/theme/colors.ts

Somehow I added the incorrect peacock color values when migrating theme over to here.

fix(@air/zephyr): fix incorrect peacock050 - peacock400 HEX values

---

.storybook/preview-head.html
packages/zephyr/src/theme/fonts.ts

BREAKING CHANGE: Update display font from `display` to `Gelica` and body font from `system-ui` to
`Inter`
- Update font names

feat(@air/zephyr): update display and body fonts

---

packages/zephyr/src/Button.tsx

fix(@air/zephyr): fix button size type

---

packages/zephyr/package.json
yarn.lock

Fix ACQ-83
- Upgrade framer motion to >3.0
@kylemh tested all usage of framer-motion and everything seems fine.

chore(@air/zephyr): upgrade framer motion to >3.0

---

packages/zephyr/src/Modals/ModalOverlay.tsx

look at me devving from my phone 🤞 this works

fix(@air/zephyr/modal): no set z-index on modal overlay

---

packages/icons/src/svgs/uncategorized/GoogleDrive.svg

Add three paths to google drive svg to set correct colors

style: add three paths to google drive icon

---

packages/zephyr/src/Forms/SingleSelect.tsx
packages/zephyr/src/Modals/TransactionModal.tsx

Work that I saw needed doing after https://github.com/AirLabsTeam/next/pull/627/files

Some Tweaks To SingleSelect + TransactionModal

---

packages/icons/src/svgs/uncategorized/Devices.svg

Breaking change: replacing `Devices` icon with new svg from Mari

Add new Devices icon

---

packages/zephyr/src/Modals/Modal.tsx
packages/zephyr/src/Modals/ModalContent.tsx
packages/zephyr/src/Modals/ModalOverlay.tsx
packages/zephyr/stories/modals/Modal.stories.tsx

As described here: https://www.framer.com/api/motion/component/#custom-components
> In addition, motion() must not be called inside a React render function.
Thanks for the find @dwilt

Fix modal re-rendering when content was dynamic

---

packages/zephyr/src/Forms/Input.tsx
packages/zephyr/src/Forms/SingleSelect.tsx
packages/zephyr/src/theme/variants/field.ts
packages/zephyr/stories/forms/Input.stories.tsx
packages/zephyr/stories/forms/SingleSelect.stories.tsx

Can you imagine if we _didn't_ have Chromatic right now?! 😬 
Also... desperately in need of Stitches.

Allow form fields to be 48px high

---

packages/icons/src/svgs/uncategorized/Ellipsis.svg
packages/icons/src/svgs/uncategorized/EllipsisVertical.svg

fix(@air/zephyr): fix ellipsis icon path

---

packages/zephyr/src/theme/variants/text.ts
packages/zephyr/stories/Text.stories.tsx

- add in text-ui-10-uppercase, text-ui-12-uppercase, text-ui-14-uppercase 
- update properties to
match each object to prevent conflict with responsive variants

fix(@air/zephyr): update text variants

---

packages/zephyr/src/Box.tsx
packages/zephyr/src/Tooltip.tsx

hopefully this is the last time

@air/zephyr - Box types

---

packages/zephyr/src/Forms/SingleSelect.tsx

Noticed issues with using the Cypress command for this component.

fix(@air/zephyr/singleselect): adjust ID values

---

packages/zephyr/src/Menus/abstractions/DropdownMenu.tsx

- Add in testid to dropdown menu

fix(@air/zephyr): add in testid to dropdown menu items

---

packages/zephyr/src/Menus/abstractions/DropdownMenu.tsx
packages/zephyr/stories/menus/components/MenuItem.stories.tsx

- Fix onChange type
- Add top and bottom divider menu item story

fix(@air/zephyr): make onChange optional for dropdown menu

---

packages/zephyr/src/Menus/abstractions/ContextMenu.tsx

- Add in missing dataset value

fix(@air/zephyr): add in missing dataset to context menu

---

packages/zephyr/src/Menus/abstractions/ContextMenu.tsx
packages/zephyr/src/Menus/abstractions/DropdownMenu.tsx

- Allow access to the `animation` prop

feat(@air/zephyr): allow control over menu animations

---

packages/zephyr/src/Menus/abstractions/ContextMenu.tsx
packages/zephyr/stories/menus/abstractions/ContextMenu.stories.tsx

- Add in children top and bottom props

feat(@air/zephyr): add in children top and bottom props to context menu

---

packages/zephyr/src/Modals/Modal.tsx

Fix `XButton` size for Modal to match [design](https://www.figma.com/file/EZ1hzsmsNYblYoBQYvVgEV/Web-Component-Library?node-id=1845%3A3886)

fix: fix XButton size on Modal

---

packages/zephyr/src/EditableText.tsx
packages/zephyr/stories/EditableText.stories.tsx

@kylemh `tx` prop typing is a nightmare

feat(@air/zephyr): add in maxLength, behavior and child style keys to editable text

---

packages/zephyr/src/Modals/TransactionModal.tsx
packages/zephyr/stories/modals/TransactionModal.stories.tsx

Adds the ability to have a tertiary modal within the current modal

feat: adds tertiary option to transaction modal

---

packages/zephyr/src/Forms/SingleSelect.tsx
packages/zephyr/stories/forms/SingleSelect.stories.tsx

- Adds optional `data-testid` prop on the SelectOptions in the SingleSelect component

fix: adds optional testId for options in singleSelect dropdown

---

packages/zephyr/src/theme/colors.ts

Revert colors to unblock updating package

revert(@air/zephyr): revert colors update

---

packages/zephyr/src/Modals/TransactionModal.tsx

- Updates the doc block for the tertiaryCTA to inform consumers about the default behavior

chore: updates the docBlock for tertiaryCTA to explain default button

---

packages/zephyr/src/theme/variants/text.ts
packages/zephyr/stories/Text.stories.tsx
yarn.lock

Adds font size 8 to variants - needed for lettering displayed within timestamp markers on videos

feat(text): add font size 8

---

packages/zephyr/src/theme/variants/button.ts

Fix active colors for blue and destructive ghost buttons

fix: fix active colors for blue and destructive ghost buttons

---

packages/zephyr/src/IconButton.tsx

- Fix IconButton types to require the necessary props for Tooltip

fix/req tooltip props on iconButton

---

packages/zephyr/src/Tooltip.tsx

- Fixes the prop types on tooltip

fix/ the props type

---

packages/zephyr/src/Tooltip.tsx
packages/zephyr/stories/Tooltip.stories.tsx

- BREAKING CHANGE: remove props
- removes `withBorder` prop

fix/remove withBorder prop from tooltip

---

packages/zephyr/src/Menus/abstractions/ContextMenu.tsx

fix: added missing key to ContextMenu suboptions

---

packages/zephyr/src/RadixMenu/abstractions/RadixDropdownMenu.tsx
packages/zephyr/src/RadixMenu/components/RadixMenuItem.tsx

Add `subOptionsTx` prop to style `subOptions` container - need this to fix bug with sub options menu scroll

Add subOptionsTxProp
